[package]
name    = "mu_jig"
version = "0.1.0"
edition = "2021"


[lib]
name = "mu_jig"
path = "src/lib.rs"

[[bin]]
name = "mu_jig"
path = "src/main.rs"


members = [
    "my_binary",
    "pdbtbx"
]

[dependencies]
nom = "7.1.3"
pdbtbx = { path = "../pdbtbx" }
